require("config.options")
require("config.runtime")
require("config.keymaps")
require("config.autocmds")
require("ui.layout").setup()
require("game").setup()
require("ai").setup()
require("config.lazy")
